### ISSUE TITLE
colocated cube pair

### ISSUE THREAD

**Issue by marqh** [CubeBrowser/cube-explorer#7] opened 2016-03-02 11:57 UTC
Co-located cubes shall be rendered as sets, with shared sliders across non-plot dimensions, producing similar results to

```
import os

import iris
import iris.plot as iplt
import matplotlib.pyplot as plt
import requests

def get_files():

    # http://docs.python-requests.org/en/master/api/?highlight=iter_content#requests.Response.iter_content
    # The chunk size is the number of bytes it should read into memory. This is not necessarily the length of each item returned as decoding can take place.
    chunk_size = 2**20

    if not os.path.exists('files'):
        os.mkdir('files')

    uris = ['http://thredds.3dvis.informaticslab.co.uk/thredds/fileServer/testLab/umqvaa_cloud_volume_fraction_in_atmosphere_layer_20160301T0900Z_pc002.nc',
            'http://thredds.3dvis.informaticslab.co.uk/thredds/fileServer/testLab/umqvaa_cloud_volume_fraction_in_atmosphere_layer_20160301T0900Z_pc004.nc',
            'http://thredds.3dvis.informaticslab.co.uk/thredds/fileServer/testLab/umqvaa_cloud_volume_fraction_in_atmosphere_layer_20160301T0900Z_pc006.nc',
        'http://thredds.3dvis.informaticslab.co.uk/thredds/fileServer/testLab/umqvaa_air_temperature_20160301T0900Z_pc002.nc',
            'http://thredds.3dvis.informaticslab.co.uk/thredds/fileServer/testLab/umqvaa_air_temperature_20160301T0900Z_pc004.nc',
            'http://thredds.3dvis.informaticslab.co.uk/thredds/fileServer/testLab/umqvaa_air_temperature_20160301T0900Z_pc006.nc',
            'http://thredds.3dvis.informaticslab.co.uk/thredds/fileServer/testLab/ukv_orog.pp']

    for uri in uris:
        filename = 'files/{}'.format(uri.split('/')[-1])
        if not os.path.isfile(filename):
            print('downloading {}'.format(uri))
            print('...')
            r = requests.get(uri, stream=True)
            with open(filename, 'wb') as fd:
                for chunk in r.iter_content(chunk_size):
                    fd.write(chunk)

def load_data():
    iris.FUTURE.netcdf_promote = True
    cubes = iris.load('files/*')
    cubes = cubes.concatenate()

    # for cube in cubes:
    #     print cube
    return cubes

def axes_pair(a, b, i):
    if not os.path.exists('pics'):
        os.mkdir('pics')
    plt.subplot(1, 2, 1)
    iplt.contour(b)
    plt.title(b.name())
    plt.gca().coastlines()
    plt.subplot(1, 2, 2)
    iplt.pcolormesh(a)
    plt.title(a.name())
    plt.gca().coastlines()
    plt.savefig('pics/{}.png'.format(i))

def plot_slices(cubes):
    airt = cubes.extract('air_temperature', strict=True)
    airt.coord(axis='x').guess_bounds()
    airt.coord(axis='y').guess_bounds()
    airt_2d_hz = airt.slices([airt.coord(axis='x'), airt.coord(axis='y')])
    cloudv = cubes.extract('cloud_volume_fraction_in_atmosphere_layer', strict=True)
    cloudv_2d_hz = cloudv.slices([cloudv.coord(axis='x'), cloudv.coord(axis='y')])

    for i, (at, cv) in enumerate(zip(airt_2d_hz, cloudv_2d_hz)):
        axes_pair(at, cv, i)

def main():
    get_files()
    cubes = load_data()
    plot_slices(cubes)

if __name__ == '__main__':
    main()

```

**Comment by marqh** [comment] 2016-03-02 11:58
@jbednar @philippjfr @jlstevens

**Comment by philippjfr** [comment] 2016-03-02 11:59
Thanks @marqh! Should have an example by the next meeting.

**Comment by jlstevens** [comment] 2016-03-02 12:05
Thanks! 

I'll trying this out shortly to have a better idea what this data looks like.

**Comment by jlstevens** [comment] 2016-03-08 00:26
I should be able to demo a nice notebook based on this user story soon but right now I can't seem to ping or get any response from http://thredds.3dvis.informaticslab.co.uk.

I've tried using requests as follows both on JupyterHub and on my local machine using this example:

``` python
requests.get('http://thredds.3dvis.informaticslab.co.uk/thredds/fileServer/testLab/umqvaa_cloud_volume_fraction_in_atmosphere_layer_20160301T0900Z_pc002.nc', stream=True)
```

Unfortunately this fails with a `ConnectionError: Connection refused` . Is this data is currently unavailable from this server?

**Comment by marqh** [comment] 2016-03-08 15:43
http://thredds.3dvis.informaticslab.co.uk/thredds/catalog/testLab/catalog.html

**Comment by marqh** [comment] 2016-03-08 15:43
on one of these  pick the HTTPServer: option for a direct download

I am not aware why some of these 404 and others do not

**Comment by jlstevens** [comment] 2016-03-08 18:17
@marqh Thanks for the link to the catalog! 

I'll have another go fetching the files mentioned in the example and hopefully most of them will be available...

**Edit:** There are no links in your last comment...I assume you'll update it once you have a list of suitable servers?

**Comment by jlstevens** [comment] 2016-03-08 20:49
Just to say I've just gone through all the URIs in the example above and all give me 404s except the last one.

For now, I'm going to assume I can use any three of the `umqvaa_cloud_volume_fraction_in_atmosphere_layer_*.nc` and any three of the `umqvaa_air_temperature_*.nc` files listed in the catalog and see how that goes!

**Comment by philippjfr** [comment] 2016-03-08 20:50
Odd, just tried the first three and they all worked for me.

**Comment by jlstevens** [comment] 2016-03-08 20:53
Ah, I can't seem to fetch them via requests but direct downloads in the browser seem fine!

I'll grab those files now and I can figure out how to get them via Python later...

**Edit:** To clarify the ones in the example still don't work but there is plenty I can use from the catalog

**Comment by philippjfr** [comment] 2016-03-08 21:03
To clarify as well, the example URIs also don't work for me, I meant the first three from the catalogue.

**Comment by jlstevens** [comment] 2016-03-08 21:25
Well, after all that confusion, I _have_ finally managed to get the exact files used in the above example by using JupyterHub (which wasn't working earlier on)! I'm not quite sure what is going on but at least I can now try the example.

Unfortunately, I'm running into a problem on this line:

``` python
cubes = iris.load('files/*')
```

Here is the exception:

```
ValueError: No format specification could be found for the given buffer. 
File element cache:
 {'FileExtension()': '.nc', 'LeadingLine()': '\r\n', 
'MagicNumber(8, None)': '939577809079766282', 
'UriProtocol()': 'file', 'MagicNumber(4, None)': '218762506', 
'MagicNumber(100, None)': '\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n
<html xmlns="http://www.w3.org...'}
```

Any idea why loading isn't working as expected? Thanks!

**Edit:** After a little googling, I expect the error was generated by this [line](https://github.com/SciTools/iris/blob/master/lib/iris/io/format_picker.py#L150) in `format_pickler.py`.

**Comment by marqh** [comment] 2016-03-09 11:39
jeepers, this data source is not being helpful at all

that error is coming in because a file format is not understood 

rather than 

```
cubes = iris.load('files/*')
```

try

```
cubes = iris.cube.CubeList()
import glob
for f in glob.glob(files/*):
    try:
        cubes.append(iris.load(f))
    except Exception:
        print(f)
```

and see which files it chokes on, then remove them; they'll likely be broken downloads

better data sets are clearly required

**Comment by jlstevens** [comment] 2016-03-15 10:26
Unfortunately, the loading step is choking on all the files mentioned above with the exception of 'ukv_orog.pp' which does load. Given that file, it progresses to `plot_slices` but then fails in the `airt = cubes.extract('air_temperature', strict=True)` step with:

```
AttributeError: 'CubeList' object has no attribute 'ndim'
```

**Comment by jlstevens** [comment] 2016-03-15 10:39
I notice that the file that successfully loads has the `.pp` extension while the others have the `.nc` extension. I'm not yet familiar with what these  file extensions signify but maybe the issue is related to that?

**Comment by jlstevens** [comment] 2016-04-04 20:31
A notebook called `Colocated_cube_pair` is now available [here](https://github.com/ContinuumIO/cube-explorer/blob/master/notebooks/Colocated_cube_pair.ipynb) to demonstrate this functionality. It can also be tested live on our  [JupyterHub](http://metoffice.continuum.io:8000).

I am happy to commit this straight to master, submit a PR or maybe hold back if you have any other improvements or suggestions you would prefer to see implemented first. If you are happy to merge in this notebook, I think we can close this issue!

**Comment by jlstevens** [comment] 2016-04-05 12:42
The PR referenced above has been merged.

Any suggestions on how to extend or improve this notebook are welcome but they should be filed as new issues to target specific changes.

**Closed as completed by jlstevens** 2016-04-05 12:42 UTC
